branch-defaults:
  default:
    environment: emotionmap
    group_suffix: null
global:
  application_name: emotion_map
  default_ec2_keyname: aws-5Vs
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
