branch-defaults:
  default:
    environment: emotion-map
    group_suffix: null
global:
  application_name: django-tutorial
  default_ec2_keyname: aws-5Vs
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
